name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display root directory structure for debugging
      run: |
        echo "Root directory structure:"
        ls -R

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Confirm .NET SDK version
      run: dotnet --version

    - name: Restore dependencies
      run: |
        echo "Running dotnet restore in SpeakingRoses"
        dotnet restore SpeakingRoses/SpeakingRoses.sln

    - name: Build solution
      run: |
        echo "Building solution in SpeakingRoses"
        dotnet build SpeakingRoses/SpeakingRoses.sln --no-restore --configuration Release

    - name: Run tests
      run: |
        echo "Running tests in Tests project"
        dotnet test Tests/Tests.csproj --no-build --verbosity normal --configuration Release
