name: CI Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      

      - name: List files in repository
        run: ls -R

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Technical-Test-Speaking-Roses/SpeakingRoses/SpeakingRoses.sln

      - name: Build
        run: dotnet build Technical-Test-Speaking-Roses/SpeakingRoses/SpeakingRoses.sln --no-restore

      - name: Run tests
        run: dotnet test Technical-Test-Speaking-Roses/Tests/Tests.csproj
